jobs:
  auto-assign:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: ${{ always() }}
      name: Sets label 09 Pending Peer Review
      uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: 09 Pending Peer Review
        repo-token: ${{ secrets.GITHUB_TOKEN }}
name: Pull Request Assignment
on:
  repository_dispatch:
    types: trigger-ga___auto-assign-pull-requests.yml
permissions:
  contents: read
  pull-requests: write
