jobs:
  build-app:
    name: Build with gradle
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out the repo
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up Java JDK 11
      uses: actions/setup-java@v3
      with:
        architecture: x64
        distribution: temurin
        java-package: jdk
        java-version: 11
    - continue-on-error: true
      env:
        ADEMPIERE_LIBRARY_VERSION: test-version
      name: Build with Gradle
      run: gradle build
name: ADempiere Build With gradle
on:
  repository_dispatch:
    types: trigger-ga___build_with_gradle.yml
