jobs:
  build-app:
    name: Publish with gradle to maven central
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out the repo
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up Java JDK 11
      uses: actions/setup-java@v3
      with:
        architecture: x64
        distribution: temurin
        java-package: jdk
        java-version: 11
    - continue-on-error: true
      env:
        ADEMPIERE_LIBRARY_VERSION: ${{ github.event.release.tag_name }}
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.PGP_SECRET }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PGP_PASSPHRASE }}
        ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.OSSRH_TOKEN }}
        ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.OSSRH_USERNAME }}
      name: Publish with Gradle
      run: gradle publish
name: Publish With gradle to maven central
on:
  repository_dispatch:
    types: trigger-ga___publish_with_gradle.yml
