jobs:
  publish:
    runs-on: self-hosted
    services:
      postgres:
        env:
          POSTGRES_PASSWORD: postgres
        image: postgres:14.6
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
        ports:
        - 5432:5432
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-package: jdk
        java-version: '11'
    - continue-on-error: true
      name: Build Adempiere with database restore...
      uses: ./.github/actions/adempiere-build
      with:
        nodbrestore: false
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_ACCESS }}
      name: Upload zip
      uses: skx/github-action-publish-binaries@master
      with:
        args: install/build/*.zip
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_ACCESS }}
      name: Upload zip.MD5
      uses: skx/github-action-publish-binaries@master
      with:
        args: install/build/*.zip.MD5
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_ACCESS }}
      name: Upload tar.gz
      uses: skx/github-action-publish-binaries@master
      with:
        args: install/build/*.tar.gz
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_ACCESS }}
      name: Upload tar.MD5
      uses: skx/github-action-publish-binaries@master
      with:
        args: install/build/*.tar.gz.MD5
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_ACCESS }}
      name: Upload Seed (Database)
      uses: skx/github-action-publish-binaries@master
      with:
        args: adempiere/Adempiere/data/Adempiere_pg.dmp
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_ACCESS }}
      name: Upload Compressed Seed (Database)
      uses: skx/github-action-publish-binaries@master
      with:
        args: adempiere/Adempiere/data/Adempiere_pg.jar
name: ADempiere Publish
on:
  repository_dispatch:
    types: trigger-ga___release.yml
